name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Para las pruebas
          
      - name: Run Tests
        run: |
          pytest  # Ejecuta tus pruebas automáticas

  build-and-test-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t mapa-logistica .

      - name: Run Container
        run: |
          docker run -d -p 8050:8050 --name test-app mapa-logistica
          # Esperar a que Gunicorn/Dash arranquen (Healthcheck manual)
          sleep 5 
      
      - name: Verify API Health
        run: curl --fail http://localhost:8050/health | grep "connected"

      - name: Check App Response
        run: |
          # Intentamos descargar el HTML de la app
          # --fail hace que el comando falle si el status no es 200
          # --silent evita llenar el log de basura
          curl --fail --silent http://localhost:8050 | grep "Gestión de Cargas"
          
      - name: Container Logs on Failure
        if: failure()
        run: docker logs test-app